// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: airmobility/sdsp_a.proto

package airmobility

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AirMobilityAPIClient is the client API for AirMobilityAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirMobilityAPIClient interface {
	// 空間情報登録
	//
	// オブジェクトを空間ID群で登録する。
	PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error)
	// 空間情報取得
	//
	// オブジェクトの値を得る
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (AirMobilityAPI_GetObjectClient, error)
	// 空間情報削除
	//
	// 空間情報を削除する。
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// 指定領域空間情報取得
	//
	// 指定した領域のリスク値などの空間情報の値を得る。
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (AirMobilityAPI_GetValueClient, error)
	// 飛行計画登録（予約）
	//
	// 飛行計画（各種形状の空域空間）を空間ID群で登録する。
	// 重複はエラー
	PutReserveArea(ctx context.Context, in *PutReserveAreaRequest, opts ...grpc.CallOption) (*PutReserveAreaResponse, error)
	// 飛行許容空域取得
	//
	// 指定した領域および時刻を指定し、飛行許容領域の空間ID群を得る。
	// 空域空間の値の取得にはGetValue()を利用する。
	// 飛行許容領域は下記を含まない領域
	//・バリア
	//・飛行制限空域
	//・緊急用務空域
	//・飛行計画空域
	//・オーバーレイ
	SelectAirspaceArrangement(ctx context.Context, in *SelectAirspaceArrangementRequest, opts ...grpc.CallOption) (*SelectAirspaceArrangementResponse, error)
	// 飛行許容空域取得（ストリーム）
	//
	// 指定した領域および時刻で飛行可能な空域空間の空間ID群をストリームで得る。
	// 次のようなケースに利用する。
	// ・大量のデータを分割して取得
	// ・変化を取得
	SelectAirspaceArrangementStream(ctx context.Context, in *SelectAirspaceArrangementRequest, opts ...grpc.CallOption) (AirMobilityAPI_SelectAirspaceArrangementStreamClient, error)
}

type airMobilityAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAirMobilityAPIClient(cc grpc.ClientConnInterface) AirMobilityAPIClient {
	return &airMobilityAPIClient{cc}
}

func (c *airMobilityAPIClient) PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error) {
	out := new(PutObjectResponse)
	err := c.cc.Invoke(ctx, "/uas.airmobility.v3.AirMobilityAPI/PutObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airMobilityAPIClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (AirMobilityAPI_GetObjectClient, error) {
	stream, err := c.cc.NewStream(ctx, &AirMobilityAPI_ServiceDesc.Streams[0], "/uas.airmobility.v3.AirMobilityAPI/GetObject", opts...)
	if err != nil {
		return nil, err
	}
	x := &airMobilityAPIGetObjectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AirMobilityAPI_GetObjectClient interface {
	Recv() (*Object, error)
	grpc.ClientStream
}

type airMobilityAPIGetObjectClient struct {
	grpc.ClientStream
}

func (x *airMobilityAPIGetObjectClient) Recv() (*Object, error) {
	m := new(Object)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *airMobilityAPIClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, "/uas.airmobility.v3.AirMobilityAPI/DeleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airMobilityAPIClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (AirMobilityAPI_GetValueClient, error) {
	stream, err := c.cc.NewStream(ctx, &AirMobilityAPI_ServiceDesc.Streams[1], "/uas.airmobility.v3.AirMobilityAPI/GetValue", opts...)
	if err != nil {
		return nil, err
	}
	x := &airMobilityAPIGetValueClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AirMobilityAPI_GetValueClient interface {
	Recv() (*Objects, error)
	grpc.ClientStream
}

type airMobilityAPIGetValueClient struct {
	grpc.ClientStream
}

func (x *airMobilityAPIGetValueClient) Recv() (*Objects, error) {
	m := new(Objects)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *airMobilityAPIClient) PutReserveArea(ctx context.Context, in *PutReserveAreaRequest, opts ...grpc.CallOption) (*PutReserveAreaResponse, error) {
	out := new(PutReserveAreaResponse)
	err := c.cc.Invoke(ctx, "/uas.airmobility.v3.AirMobilityAPI/PutReserveArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airMobilityAPIClient) SelectAirspaceArrangement(ctx context.Context, in *SelectAirspaceArrangementRequest, opts ...grpc.CallOption) (*SelectAirspaceArrangementResponse, error) {
	out := new(SelectAirspaceArrangementResponse)
	err := c.cc.Invoke(ctx, "/uas.airmobility.v3.AirMobilityAPI/SelectAirspaceArrangement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airMobilityAPIClient) SelectAirspaceArrangementStream(ctx context.Context, in *SelectAirspaceArrangementRequest, opts ...grpc.CallOption) (AirMobilityAPI_SelectAirspaceArrangementStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AirMobilityAPI_ServiceDesc.Streams[2], "/uas.airmobility.v3.AirMobilityAPI/SelectAirspaceArrangementStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &airMobilityAPISelectAirspaceArrangementStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AirMobilityAPI_SelectAirspaceArrangementStreamClient interface {
	Recv() (*AirspaceArrangement, error)
	grpc.ClientStream
}

type airMobilityAPISelectAirspaceArrangementStreamClient struct {
	grpc.ClientStream
}

func (x *airMobilityAPISelectAirspaceArrangementStreamClient) Recv() (*AirspaceArrangement, error) {
	m := new(AirspaceArrangement)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AirMobilityAPIServer is the server API for AirMobilityAPI service.
// All implementations must embed UnimplementedAirMobilityAPIServer
// for forward compatibility
type AirMobilityAPIServer interface {
	// 空間情報登録
	//
	// オブジェクトを空間ID群で登録する。
	PutObject(context.Context, *PutObjectRequest) (*PutObjectResponse, error)
	// 空間情報取得
	//
	// オブジェクトの値を得る
	GetObject(*GetObjectRequest, AirMobilityAPI_GetObjectServer) error
	// 空間情報削除
	//
	// 空間情報を削除する。
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// 指定領域空間情報取得
	//
	// 指定した領域のリスク値などの空間情報の値を得る。
	GetValue(*GetValueRequest, AirMobilityAPI_GetValueServer) error
	// 飛行計画登録（予約）
	//
	// 飛行計画（各種形状の空域空間）を空間ID群で登録する。
	// 重複はエラー
	PutReserveArea(context.Context, *PutReserveAreaRequest) (*PutReserveAreaResponse, error)
	// 飛行許容空域取得
	//
	// 指定した領域および時刻を指定し、飛行許容領域の空間ID群を得る。
	// 空域空間の値の取得にはGetValue()を利用する。
	// 飛行許容領域は下記を含まない領域
	//・バリア
	//・飛行制限空域
	//・緊急用務空域
	//・飛行計画空域
	//・オーバーレイ
	SelectAirspaceArrangement(context.Context, *SelectAirspaceArrangementRequest) (*SelectAirspaceArrangementResponse, error)
	// 飛行許容空域取得（ストリーム）
	//
	// 指定した領域および時刻で飛行可能な空域空間の空間ID群をストリームで得る。
	// 次のようなケースに利用する。
	// ・大量のデータを分割して取得
	// ・変化を取得
	SelectAirspaceArrangementStream(*SelectAirspaceArrangementRequest, AirMobilityAPI_SelectAirspaceArrangementStreamServer) error
	mustEmbedUnimplementedAirMobilityAPIServer()
}

// UnimplementedAirMobilityAPIServer must be embedded to have forward compatible implementations.
type UnimplementedAirMobilityAPIServer struct {
}

func (UnimplementedAirMobilityAPIServer) PutObject(context.Context, *PutObjectRequest) (*PutObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutObject not implemented")
}
func (UnimplementedAirMobilityAPIServer) GetObject(*GetObjectRequest, AirMobilityAPI_GetObjectServer) error {
	return status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedAirMobilityAPIServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedAirMobilityAPIServer) GetValue(*GetValueRequest, AirMobilityAPI_GetValueServer) error {
	return status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedAirMobilityAPIServer) PutReserveArea(context.Context, *PutReserveAreaRequest) (*PutReserveAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutReserveArea not implemented")
}
func (UnimplementedAirMobilityAPIServer) SelectAirspaceArrangement(context.Context, *SelectAirspaceArrangementRequest) (*SelectAirspaceArrangementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectAirspaceArrangement not implemented")
}
func (UnimplementedAirMobilityAPIServer) SelectAirspaceArrangementStream(*SelectAirspaceArrangementRequest, AirMobilityAPI_SelectAirspaceArrangementStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SelectAirspaceArrangementStream not implemented")
}
func (UnimplementedAirMobilityAPIServer) mustEmbedUnimplementedAirMobilityAPIServer() {}

// UnsafeAirMobilityAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirMobilityAPIServer will
// result in compilation errors.
type UnsafeAirMobilityAPIServer interface {
	mustEmbedUnimplementedAirMobilityAPIServer()
}

func RegisterAirMobilityAPIServer(s grpc.ServiceRegistrar, srv AirMobilityAPIServer) {
	s.RegisterService(&AirMobilityAPI_ServiceDesc, srv)
}

func _AirMobilityAPI_PutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirMobilityAPIServer).PutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uas.airmobility.v3.AirMobilityAPI/PutObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirMobilityAPIServer).PutObject(ctx, req.(*PutObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirMobilityAPI_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AirMobilityAPIServer).GetObject(m, &airMobilityAPIGetObjectServer{stream})
}

type AirMobilityAPI_GetObjectServer interface {
	Send(*Object) error
	grpc.ServerStream
}

type airMobilityAPIGetObjectServer struct {
	grpc.ServerStream
}

func (x *airMobilityAPIGetObjectServer) Send(m *Object) error {
	return x.ServerStream.SendMsg(m)
}

func _AirMobilityAPI_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirMobilityAPIServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uas.airmobility.v3.AirMobilityAPI/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirMobilityAPIServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirMobilityAPI_GetValue_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetValueRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AirMobilityAPIServer).GetValue(m, &airMobilityAPIGetValueServer{stream})
}

type AirMobilityAPI_GetValueServer interface {
	Send(*Objects) error
	grpc.ServerStream
}

type airMobilityAPIGetValueServer struct {
	grpc.ServerStream
}

func (x *airMobilityAPIGetValueServer) Send(m *Objects) error {
	return x.ServerStream.SendMsg(m)
}

func _AirMobilityAPI_PutReserveArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutReserveAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirMobilityAPIServer).PutReserveArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uas.airmobility.v3.AirMobilityAPI/PutReserveArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirMobilityAPIServer).PutReserveArea(ctx, req.(*PutReserveAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirMobilityAPI_SelectAirspaceArrangement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectAirspaceArrangementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirMobilityAPIServer).SelectAirspaceArrangement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uas.airmobility.v3.AirMobilityAPI/SelectAirspaceArrangement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirMobilityAPIServer).SelectAirspaceArrangement(ctx, req.(*SelectAirspaceArrangementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirMobilityAPI_SelectAirspaceArrangementStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SelectAirspaceArrangementRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AirMobilityAPIServer).SelectAirspaceArrangementStream(m, &airMobilityAPISelectAirspaceArrangementStreamServer{stream})
}

type AirMobilityAPI_SelectAirspaceArrangementStreamServer interface {
	Send(*AirspaceArrangement) error
	grpc.ServerStream
}

type airMobilityAPISelectAirspaceArrangementStreamServer struct {
	grpc.ServerStream
}

func (x *airMobilityAPISelectAirspaceArrangementStreamServer) Send(m *AirspaceArrangement) error {
	return x.ServerStream.SendMsg(m)
}

// AirMobilityAPI_ServiceDesc is the grpc.ServiceDesc for AirMobilityAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirMobilityAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uas.airmobility.v3.AirMobilityAPI",
	HandlerType: (*AirMobilityAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutObject",
			Handler:    _AirMobilityAPI_PutObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _AirMobilityAPI_DeleteObject_Handler,
		},
		{
			MethodName: "PutReserveArea",
			Handler:    _AirMobilityAPI_PutReserveArea_Handler,
		},
		{
			MethodName: "SelectAirspaceArrangement",
			Handler:    _AirMobilityAPI_SelectAirspaceArrangement_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetObject",
			Handler:       _AirMobilityAPI_GetObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetValue",
			Handler:       _AirMobilityAPI_GetValue_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SelectAirspaceArrangementStream",
			Handler:       _AirMobilityAPI_SelectAirspaceArrangementStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "airmobility/sdsp_a.proto",
}
